App name as a parameter.
oaleynik/nwjs-autoupdater pull request #7
Opened 2017-05-16 14:04 UTC by rsfernandes

Hi! 

First I want to thank you for this updater to apps build with nw.js.

But I think the application executable name should be passed as a parameter. In my company cenario we have a ton of apps running with nw.js and the app exec name can chance for each application, so I need this to be variable (not "my_app").

Best regards,
Rogério Fernandes

2017-05-17 09:00 UTC, oaleynik requested changes
One tiny change and it will be good to go. Thank you!

2017-05-17 09:00 UTC, oaleynik commented on src/nwjs-autoupdater/main.go
> +	flag.StringVar(&appName, "app-name", "", "Application executable name")
@rsfernandes Can you please use `my_app` as a default value here? This will not break autoupdater for people who use it without --app-name flag :)

2017-05-17 14:34 UTC, rsfernandes commented
I did the change and tested it here. Worked passing the parameter and without it.

I'm glad to help, your project is being really helpful!

;)

2017-05-21 17:08 UTC, merged

2017-05-21 17:10 UTC, oaleynik commented
Merged! Thanks so much! 🍻